### ISSUE TITLE
controller for back-end

### ISSUE THREAD

**Issue by akbarsahata** [fasilkom-kasmanss/project_fina#3]
before creating front-end, please create controllers for some routing first 😹

**Comment by ratukhoirunnisa** [comment]
Oke siap kak

**Comment by ratukhoirunnisa** [comment]
Baru baca kak. Aku kerjain secepetnya ya kak, lagi ada job di pilkada, abis kerjaan pilkada selsai.

**Comment by akbarsahata** [comment]
@ratukhoirunnisa kapan kerjaan pilkadanya selesai? atau udah?

**Comment by ratukhoirunnisa** [comment]
Kemaren udah selesai kok kak..

**Comment by ratukhoirunnisa** [comment]
Terus skrg aku ngapain kak? Bikin controller? Controller apa?

**Comment by ratukhoirunnisa** [comment]
Kak aku gapaham kak ngerjain pake cara kakak gini. Maksudnya kemaren kan aku bikin web autodidak bgt dan itu bikin front end dulu trs baru kasih function-function. Cara aku masih berantakan bgt. Nah ini aku gangerti kak ngerjain via github, istilah yg kakak pake aja aku suka bingung. Jadi aku gapaham kak ngerjain apa dan harus ngapain😭 Aku mundur aja gapapa kok kak, kakak gausah engga enakan buat ga ngerjain web bareng aku lagi. abisnya ga paham kak bingung bgt😭kasian kakaknya juga aku nanya muluuu. Aku jg ada some jobs to do kak, ga gabut bgt kayak awal liburan, takut lama bgt kepegangnya. Controller gt aja aku gangerti kak maksudnya. Maaf kak sebelumnya. Kemaren juga sempet ga kontakan kan kita jadi sempet stop gitu, aku makin gapaham kak. Mau bikin front end juga aku gatau mau menu apa aja. Kemaren pas uts sih ada aku bikin front end web sma sumsel kalo kakak mau untuk referensi kakak. Maaf ya ka🙏🏻
